### ISSUE TITLE
Ever-changing graphs after clicking refresh button in Grafana: showing untrustworthy data

### ISSUE THREAD

**Issue by oveits** [vegasbrianc/docker-monitoring#10]
Hi Brian,
I am in the process of creating a blog, see [this link](https://oliverveits.wordpress.com/2016/11/02/how-to-set-up-docker-monitoring-via-cadvisor-influxdb-and-grafana/). 
The docker containers were created from docker-compose.yml and the Grafana graphs have been created from docker-monitoring-0.9.json of your repository.

There you can see that the numbers shown in Grafana do not look trustworthy:

![2016-10-28 21_28_18-grafana - new dashboard](https://cloud.githubusercontent.com/assets/8299115/19820611/695c58ac-9d5a-11e6-9c76-405704129b47.png)

After clicking refresh:

![2016-10-28 21_40_53-grafana - new dashboard](https://cloud.githubusercontent.com/assets/8299115/19820615/6bfcccb8-9d5a-11e6-8638-1ea6d2f430b6.png)

After running a CPU stress test and clicking refresh again:

![2016-10-28 21_42_51-grafana - new dashboard](https://cloud.githubusercontent.com/assets/8299115/19820622/6f25f1d0-9d5a-11e6-9226-cc189f51c724.png)

It looks like the graphs are created from random numbers. Have you ever seen something like this?

**Comment by oveits** [comment]
Okay, the problem was sitting in front of the computer: I thought that importing the json files will also configure and select the correct the data source. This is not the case. I still need to follow your Data Source Settings instructions on https://www.brianchristner.io/how-to-setup-docker-monitoring/. Only changes: I have tested with influxdb 0.9 instead of 0.8, and the Url: http://influxsrv:8086 does not work in my case; I need to use a real IP address instead of influxsrv (any idea, what the reason could be?).

Then I need to choose the correct data source by clicking -> on the title of each graph -> edit -> metrics -> choose influxdb on the data source drop-down list. It was set to `--grafana--` before.

Then we get trustworthy graphs like follows:
![2016-10-30 20_15_19-grafana - new dashboard q with correct data source](https://cloud.githubusercontent.com/assets/8299115/19839276/07ce37d2-9edf-11e6-8dd6-b59ad769cf07.png)

**Comment by oveits** [comment]
Maybe I was too quick in closing this issue. The data is still not trustworthy:
I have run a stress test, but Grafana is still looking wreird: during the last hour, I have run stress tests two times 5 minutes or so, by issuing the command 

```
docker run -it petarmaric/docker.cpu-stress-test
```

The CPU is looking good on cAdvisor (taken 2 minutes after start of a stress test)
![2016-10-30 21_08_06-cadvisor - _](https://cloud.githubusercontent.com/assets/8299115/19839590/f9ab8406-9ee4-11e6-9055-7262979412d6.png)
but Grafana looks weird:

![2016-10-30 21_05_35-grafana - new dashboard](https://cloud.githubusercontent.com/assets/8299115/19839566/a896fa8c-9ee4-11e6-9813-7027b76ed867.png)

In influxdb, I can see that the data is looking weird as well. Typing this into a browser

```
http://192.168.33.11:8086/query?pretty=true&db=cadvisor&q=SELECT%20%22value%22%20FROM%20%22cpu_usage_system%22
```

leads to a result like follows:

```
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu_usage_system",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2016-10-24T17:12:49.021559212Z",
                            910720000000
                        ],
                        [
                            "2016-10-24T17:12:49.032153994Z",
                            20000000
                        ],
                        [
                            "2016-10-24T17:12:49.033316234Z",
                            5080000000
                        ],
                        [
                            "2016-10-24T17:12:49.035050213Z",
                            10000000
                        ],
                        [
                            "2016-10-24T17:12:49.035512533Z",
                            7380000000
                        ],
                        [
                            "2016-10-24T17:12:49.036670715Z",
                            7000000000
                        ],
                        [
                            "2016-10-24T17:12:49.03716293Z",
                            1270000000
                        ],
                        [
                            "2016-10-24T17:12:49.037973862Z",
                            640000000
...
```

i.e. the values are often changed by the factor of 10000 within milliseconds. This looks like random data again. Do you have an idea on how to troubleshoot this?

**Comment by vegasbrianc** [comment]
Sorry for the delayed response @oveits. It's been a whirlwind of Docker presentations the last few days. It looks as though the query might be inaccurate. Let me startup the stack this week and have a look and get back to you.

**Comment by oveits** [comment]
Hi Brian, no problem; I like your presentations: I have seen your docker monitoring presentation on YouTube. Is there any other presentation available you can recommend?

**Comment by vegasbrianc** [comment]
I follow Prometheus quite closely and the recent PromCon had some great presentations - https://www.youtube.com/channel/UC4pLFely0-Odea4B2NL1nWA

**Comment by vegasbrianc** [comment]
@oveits Closing this issue.  Let me know if you need anything further.

**Comment by oveits** [comment]
Hi Brian, I do not regard the issue as resolved. When you follow my blog, you get random numbers from InfluxDB and it is still not clear, where I am doing wrong. In your installation, do the numbers look differently? 
However, if the recommendation is to go for Prometheus instead of the cadvisor + InfluxDB solution, I can live with it.
Best regards, Oliver

**Comment by vegasbrianc** [comment]
Hi @oveits I recommend trying Prometheus as this is the solution I am mostly working with and recommending to others. Here is my Prometheus project - https://github.com/vegasbrianc/prometheus

Let me know if you have any questions as I update this project much more often.

**Comment by oveits** [comment]
Ok, thanks. When we will approach the ops phase of my DevOps project, I will evaluate the Prometheus solution, then.

Von meinem iPhone gesendet
