### ISSUE TITLE
A small issue～

### ISSUE THREAD

**Issue by mysterytree** [vegasbrianc/docker-monitoring#2]
Get the datasource not found error  after  execute docker-compose  up and import docker-monitoring.json

May fixed it .

docker-monitoring.json
line 96 
"datasource": "influxdb",     =>   "datasource": "cadvisor",

**Comment by vegasbrianc** [comment]
The error is coming when you try to import the json file?

It sounds like the datasources are not configured correctly. Please take a look at the [Troubleshooting section](https://www.brianchristner.io/how-to-setup-docker-monitoring/)

**Comment by mysterytree** [comment]
Can Infludb+granfana  monitor several cadvisor(different server) at the same time?
Prometheus can get different cadivisor data and show them in a common charts.
In order to monitor  docker swarm cluster , 
promtheus+promdash  /  inflexdb+granfana,
which one is better ?

**Comment by vegasbrianc** [comment]
Yes, both influxdb & prometheus can monitor multiple cadvisors. I personally like using Prometheus as it it meets my needs much better and it is has a lot more features built in (Alerting, exporters, short lived jobs, etc)

**Comment by mysterytree** [comment]
Thanks for your help...
I also tried the prom-alertmanager .. 
Actually also make me crazy....
for example,
I write the rules

```
ALERT StartContainer
IF time()-container_start_time_seconds < 20
FOR 15s
WITH {
job="cadvisor"
}
SUMMARY "Instance {{$labels.name}} start"
DESCRIPTION "{{$labels.instance}} of job {{$labels.job}} start,id: {{$labels.id}}"
```

Message send to slack all the time ..Almost one time per minutes .
This situation last 6-7 minutes and the alert stopped...

Fortunately，the project update quickly and maybe every thing would be ok in future..
Thanks again.
