### ISSUE TITLE
Broken with InfluxDB 0.9.x and latest cAdvisor PR (to support 0.9.x)

### ISSUE THREAD

**Issue by marcellodesales** [vegasbrianc/docker-monitoring#3]
Hi @vegasbrianc 

Thanks a lot for the awesome tutorial on monitoring https://www.brianchristner.io/how-to-setup-docker-monitoring/... I'm trying to get the InfluxDB 0.9.x support to work and I cannot even get the data out to InfluxDB... 

Could you please verify https://github.com/google/cadvisor/pull/1040#issuecomment-176015272? Would there be anything you could help here? I'm aware that InfluxDB 0.9.x changed and broke compatibility, so the cAdvisor team accepted this PR and I still can't get to verify it...

thanks a lot
Marcello

**Comment by marcellodesales** [comment]
The current version of your `docker-compose.yml` does not seem to work with InfluxDB 0.8.8... 

<img width="287" alt="screen shot 2016-01-28 at 12 23 35 am" src="https://cloud.githubusercontent.com/assets/131457/12638908/67c6cc76-c555-11e5-9d41-d5f4879d9b8f.png">

**Comment by marcellodesales** [comment]
@vegasbrianc Just confirmed the PR with the new changes to 0.9... https://github.com/google/cadvisor/pull/1040#issuecomment-176078952

**Comment by vegasbrianc** [comment]
Hi @marcellodesales thanks for the info. Do I need to update the compose to add Influx 0.9?

**Comment by marcellodesales** [comment]
Not until the cAdvisor team releases the version with the PR, I would think I could send you a PR with my own image... But it is up to you...

**Comment by vegasbrianc** [comment]
I would be more than happy to accept your PR.
