### ISSUE TITLE
Imported JSON graph don't work

### ISSUE THREAD

**Issue by ghost** [vegasbrianc/docker-monitoring#5]
Hello,

thanks for your work!

---

My case
![screenshot](https://cloud.githubusercontent.com/assets/13286493/13553590/99fa9732-e39f-11e5-8f45-c7aa8c3a4dd6.png)

should be
<img width="1054" alt="docker_monitoring" src="https://cloud.githubusercontent.com/assets/13286493/13553595/ac9efc7a-e39f-11e5-900e-456f77e6e8f0.png">

Can you help to adjust default json to your screenshot manner?

I use `debian 8.3 x64`, 
`docker-compose up`.

**Comment by vegasbrianc** [comment]
Hi @a93ushakov We just upgraded the versions of Grafana and InfluxDB recently. I still need to update the graphs and queries so I should have this done by the end of the week.

**Comment by ghost** [comment]
@vegasbrianc thank you for your respond and help

**Comment by vegasbrianc** [comment]
Hi @a93ushakov I finally upgraded the queries and the json to the latest versions.
