### ISSUE TITLE
Adding axes

### ISSUE THREAD

**Issue by elephunt** [vegasbrianc/docker-monitoring#7]
Hey ,can you add for screenshot what you added for axes?

**Comment by vegasbrianc** [comment]
Hi @elephunt which graph?

**Comment by vegasbrianc** [comment]
BTW @elephunt you can download the dashboard direct from https://grafana.net/dashboards/179

**Comment by elephunt** [comment]
Cool , but my data source is influxdb.,and he asking is Prometheus.

**Comment by vegasbrianc** [comment]
Did you try to import the [.8](https://github.com/vegasbrianc/docker-monitoring/blob/master/docker-monitoring-0.8.json) or [.9 ](https://github.com/vegasbrianc/docker-monitoring/blob/master/docker-monitoring-0.9.json)json files from this repo?

**Comment by elephunt** [comment]
.9

**Comment by vegasbrianc** [comment]
And this didn't import the axis?

**Comment by elephunt** [comment]
Switched from InfluxDb to Prometheus , everything works now.Thnx

**Comment by vegasbrianc** [comment]
Great news! Good luck with monitoring.
