### ISSUE TITLE
Let's Swarm it (1.12 +)

### ISSUE THREAD

**Issue by pascalandy** [vegasbrianc/docker-monitoring#8]
I want to put this into my swarm cluster (6 nodes in dev).

If I understand well **cadvisor** shall run as global (on every nodes)?

Then I guess there is some work to configure the dashboard to monitor all nodes. 

Cheers!

**Comment by vegasbrianc** [comment]
Have you had a look at my other monitoring repo - https://github.com/vegasbrianc/prometheus I've tested this with Swarm and it worked well

**Comment by pascalandy** [comment]
Never answered but yes I tried it :)
